import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth";
import DefaultLayout from "./layout/default-layout";
import { CustomThemeProvider } from "@/context/theme";
import QueryProvider from "@/context/query-client";
import { ToastContainer } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <CustomThemeProvider>
            <AuthProvider>
              <DefaultLayout>{children}</DefaultLayout>
              <ToastContainer />
            </AuthProvider>
          </CustomThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
